# Generated by Django 5.0.7 on 2026-02-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='total_purse',
            new_name='purse',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='remaining_purse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
