# Generated by Django 5.0.7 on 2026-02-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_total_purse_team_purse_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='remaining_purse',
            field=models.IntegerField(blank=True, default=900),
            preserve_default=False,
        ),
    ]
