# Generated by Django 5.0.7 on 2026-02-21 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_team_remaining_purse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='status',
        ),
        migrations.AddField(
            model_name='player',
            name='sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
