# Generated by Django 5.0.7 on 2026-02-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_player_status_player_sold_price_player_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sold', 'Sold'), ('unsold', 'Unsold')], default='pending', max_length=10),
        ),
    ]
