# Generated by Django 5.0.7 on 2026-02-21 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_player_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player'),
        ),
    ]
