# Generated by Django 5.0.7 on 2026-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
