# Generated by Django 6.0.6 on 2026-08-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auction_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='boughtplayer',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='current_bid_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_bid_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidding_on', to='app.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='BoughtPlayer',
        ),
    ]
